upstream_package_name: tmux-top
downstream_package_name: tmux-top
specfile_path: tmux-top.spec
jobs:
- job: copr_build
  targets:
  - fedora-all
  trigger: pull_request
- job: tests
  targets:
  - fedora-all
  trigger: pull_request
- job: propose_downstream
  trigger: release
  dist_git_branches:
  - fedora-all
- job: koji_build
  trigger: commit
  allowed_pr_authors: ["ttomecek", "packit"]
  dist_git_branches:
  - fedora-all
- job: bodhi_update
  trigger: commit
  dist_git_branches:
  - fedora-branched
