specfile_path: tmux-top.spec

upstream_package_name: tmux-top
upstream_project_url: https://github.com/TomasTomecek/tmux-top
downstream_package_name: tmux-top

srpm_build_deps:
- "go-vendor-tools"
- "golang-bin"
- "askalono-cli"
jobs:
- job: copr_build
  targets:
  - fedora-all
  trigger: pull_request
- job: tests
  targets:
  - fedora-all
  trigger: pull_request
- job: propose_downstream
  trigger: release
  dist_git_branches:
  - fedora-rawhide

- job: pull_from_upstream
  trigger: release
  dist_git_branches:
  - fedora-all

- job: koji_build
  trigger: commit
  allowed_pr_authors: ["ttomecek", "packit"]
  dist_git_branches:
  - fedora-all
- job: bodhi_update
  trigger: commit
  dist_git_branches:
  - fedora-branched

create_sync_note: false
actions:
  post-modifications:
    # https://fedora.gitlab.io/sigs/go/go-vendor-tools/scenarios/#manual-update
    # https://github.com/fido-device-onboard/go-fdo-server/blob/main/.packit.yaml
    - |
      bash -xeuc "
        export GOTOOLCHAIN=local+auto
        go_vendor_archive create --config go-vendor-tools.toml tmux-top.spec
        go_vendor_license \
          --config go-vendor-tools.toml \
          --path tmux-top.spec \
          report \
          --verify-spec
        if [ -n "${PACKIT_DOWNSTREAM_REPO}" ]; then
          cp "${PACKIT_UPSTREAM_REPO}/tmux-top-${PACKIT_PROJECT_VERSION}.tar.gz" "${PACKIT_DOWNSTREAM_REPO}"
          cp "${PACKIT_UPSTREAM_REPO}/tmux-top-${PACKIT_PROJECT_VERSION}-vendor.tar.bz2" "${PACKIT_DOWNSTREAM_REPO}"
        fi
      "
