# Generated by go2rpm 1.19.0
%bcond check 1

# https://github.com/TomasTomecek/tmux-top
%global goipath         github.com/TomasTomecek/tmux-top
Version:                1.0.0
%global tag             1.0.0

%gometa -L -f


Name:           tmux-top
Release:        1.20260204154827173937.s390x.test.fail.1.g8758f35%{?dist}
Summary:        Monitoring information for your tmux status line

# Generated by go-vendor-tools
License:        BSD-2-Clause AND GPL-2.0-only AND MIT
URL:            %{gourl}
Source0:        tmux-top-1.0.0.tar.gz
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
Monitoring information for your tmux status line.

tmux-top allows you to see your:

 * load
 * memory usage
 * network information
 * I/O


%prep
%goprep -p1
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/%{name} %{goipath}/cmd/tmux-top

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%doc docs README.md
%{_bindir}/tmux-top


%changelog
%autochangelog
